name: .NET Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 'latest' # Usa la última versión de Visual Studio

    - name: Restore NuGet packages
      run: nuget restore SIGEN_GUI.sln

    - name: Build Solution
      run: msbuild SIGEN_GUI.sln /p:Configuration=Release

    - name: Run Tests
      run: |
        # Asegúrate de que el archivo de pruebas DLL esté en el directorio correcto
        vstest.console.exe path/to/your/test/project.dll
